name: Check Lab HTTP status

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  fetch-urls:
    runs-on: ubuntu-latest
    permissions:
      contents: read       # Minimal permissions to access repository contents
      issues: write        # Required to create or edit comments on pull requests
    steps:
      - name: Debug variables
        run: |
          echo "Base repo: ${{ github.repository }}"
          echo "Head repo: ${{ github.event.pull_request.head.repo.full_name }}"
          echo "Head ref: ${{ github.event.pull_request.head.ref }}"
          echo "GITHUB_REPOSITORY: ${{ github.event.pull_request.head.repo.full_name }}"
          echo "BRANCH_NAME: ${{ github.event.pull_request.head.ref }}"
          echo "PR_NUMBER: ${{ github.event.number }}"

      - name: Checkout base branch
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: main
          path: base

      - name: Checkout head branch
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          path: head

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install pygithub
        run: pip install pygithub

      - name: Debug GITHUB_TOKEN Permissions
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/permissions

      - name: Get list of changed files
        id: changed-files
        run: |
          cd head
          git remote add upstream https://github.com/${{ github.repository }}
          git fetch upstream main
          git diff --name-only upstream/main..HEAD > changed_files.txt
          echo ""
          echo "Changed files:"
          cat changed_files.txt

      - name: Post comment if matching changes found
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  #${{ secrets.GH_PR_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
          BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
          HEAD_REPO: ${{ github.event.pull_request.head.repo.full_name }}
          BASE_REPO: ${{ github.repository }}
        run: |
          cd head
          python3 ../base/.github/scripts/post_lab_links.py
