name: Check Lab HTTP status

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  fetch-urls:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base branch
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: main
          path: base

      - name: Checkout head branch
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          path: head

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install pygithub
        run: pip install pygithub

      - name: Get list of changed files
        id: changed-files
        run: |
          cd head
          git remote add upstream https://github.com/galaxyproject/galaxy_codex
          git fetch upstream main
          git diff --name-only upstream/main..HEAD > changed_files.txt
          echo ""
          echo "Changed files:"
          cat changed_files.txt

      - name: Post comment if matching changes found
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PR_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
          USERNAME: ${{ github.actor }}
          BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
          GITHUB_REPOSITORY: ${{ github.event.pull_request.head.repo.full_name }}
        run: |
          cd head
          python3 ../base/.github/scripts/post_lab_links.py
