name: Check Lab HTTP status

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  post-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get list of changed files
        id: changed-files
        run: |
          git fetch origin main
          git diff --name-only origin/main..HEAD > changed_files.txt
          echo ""
          echo "Changed files:"
          cat changed_files.txt

      - name: Post comment if matching changes found
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python3 .github/scripts/post_lab_links.py
