name: Check Lab HTTP status

on:
  workflow_run:
    workflows: ["Labs diff"]
    types:
      - completed

jobs:
  test-labs:
    runs-on: ubuntu-latest
    # permissions:
    #   contents: read       # Minimal permissions to access repository contents
    #   issues: write        # Required to create or edit comments on pull requests
    steps:
      - name: Debug variables
        run: |
          echo "Base repo: ${{ github.repository }}"
          echo "Head repo: ${{ github.event.pull_request.head.repo.full_name }}"
          echo "Head ref: ${{ github.event.pull_request.head.ref }}"
          echo "GITHUB_REPOSITORY: ${{ github.event.pull_request.head.repo.full_name }}"
          echo "BRANCH_NAME: ${{ github.event.pull_request.head.ref }}"
          echo "PR_NUMBER: ${{ github.event.number }}"

      - name: Debug GITHUB_TOKEN Permissions
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/permissions

      - name: Checkout base branch
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: main
          path: base

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install pygithub
        run: pip install pygithub

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Download "Labs diff" artifact
        run: |
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
          RUN_ID=$(gh run list --workflow "Labs diff" --limit 1)
          gh run view $RUN_ID --log
          gh run download $RUN_ID --name labs_diff --dir ./labs_diff

      - name: Post comment if matching changes found
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  #${{ secrets.GH_PR_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
          BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
          HEAD_REPO: ${{ github.event.pull_request.head.repo.full_name }}
          BASE_REPO: ${{ github.repository }}
        run: |
          if [ -s labs_diff/paths.txt ]; then
            echo "Changed files found"
            cd labs_diff
            python3 base/.github/scripts/post_lab_links.py
          else
            echo "No changed files found"
          fi
