name: Test changed Labs pages

on:
  workflow_run:
    workflows: ["Labs diff"]
    types:
      - completed

jobs:
  test-labs:
    runs-on: ubuntu-latest
    # permissions:
    #   contents: read       # Minimal permissions to access repository contents
    #   issues: write        # Required to create or edit comments on pull requests
    steps:
      - name: Debug variables
        run: |
          echo "Base repo: ${{ github.repository }}"
          echo "Head repo: ${{ github.event.pull_request.head.repo.full_name }}"
          echo "Head ref: ${{ github.event.pull_request.head.ref }}"
          echo "GITHUB_REPOSITORY: ${{ github.event.pull_request.head.repo.full_name }}"
          echo "BRANCH_NAME: ${{ github.event.pull_request.head.ref }}"
          echo "PR_NUMBER: ${{ github.event.number }}"

      - name: Checkout base branch
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install pygithub
        run: pip install pygithub

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Download "Labs diff" artifact
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # gh repo set-default galaxyproject/galaxy_codex
          gh repo set-default neoformit/galaxy_codex
          RUN_ID=$(gh run list --workflow "Labs diff" --limit 1 | tail -n 1 | grep -oE '\b[0-9]{11}\b')
          echo "RUN_ID: $RUN_ID"
          gh run view $RUN_ID --log
          gh run download $RUN_ID --name labs_diff --dir ./labs_diff

      - name: Post comment if matching changes found
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  #${{ secrets.GH_PR_TOKEN }}
        run: |
          if [ -s labs_diff/paths.txt ]; then
            echo "Changed files found"
            source labs_diff/.env
            python3 ../.github/scripts/post_lab_links.py labs_diff/paths.txt
          else
            echo "No changed files found"
          fi
